/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GameDay } from "./GameDay";
export * as factories from "./factories";
export { GameDay__factory } from "./factories/GameDay__factory";
